# Generated by Django 5.1.15 on 2026-08-31 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_beds', models.PositiveIntegerField(default=100)),
                ('available_beds', models.PositiveIntegerField(default=20)),
                ('total_icu', models.PositiveIntegerField(default=20)),
                ('available_icu', models.PositiveIntegerField(default=5)),
                ('has_trauma_bay', models.BooleanField(default=True)),
                ('has_burn_unit', models.BooleanField(default=False)),
                ('has_pediatric', models.BooleanField(default=True)),
                ('has_blood_bank', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACCEPTING', 'Accepting Casualties'), ('DIVERT_SURGE', 'Surge Warning (Near Capacity)'), ('DIVERT_FULL', 'Full - Diverting Inbound'), ('OFFLINE', 'Offline / Power Loss')], db_index=True, default='ACCEPTING', max_length=30)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupied_general', models.PositiveIntegerField()),
                ('occupied_icu', models.PositiveIntegerField()),
                ('divert_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
