# Generated by Django 5.1.15 on 2026-08-31 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_index', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['node_index'],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('length_km', models.FloatField(default=1.0)),
                ('base_speed_kmh', models.FloatField(default=40.0)),
                ('hazard_multiplier', models.FloatField(default=1.0)),
                ('water_depth_cm', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('CONGESTED', 'Congested'), ('WATERLOGGED', 'Waterlogged (Slow Passage)'), ('BLOCKED', 'Blocked / Submerged')], db_index=True, default='CLEAR', max_length=30)),
                ('is_two_way', models.BooleanField(default=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_segments', to='routing.roadnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_segments', to='routing.roadnode')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
