"""
RESQ-ENG-SPEC-2026-001 — Comprehensive Hazard Pipeline Orchestration Engine (Phase 12)
Single master entry-point coordinating Phases 1 through 11 in strict physical dependency sequence.
"""

import hashlib
import json
import time
from datetime import datetime, timezone
from dataclasses import dataclass, asdict
from typing import Dict, Any, List, Optional, Union

from .core.constants import (
    MODEL_VERSION,
    SPECIFICATION_ID,
    SYSTEM_CLASSIFICATION,
)
from .scenario.dtos import ScenarioInputDTO
from .scenario.validator import validate_and_build_scenario
from .materials.dtos import MaterialPropertiesDTO
from .materials.registry import MaterialRegistry
from .source.dtos import SourceTermsDTO
from .source.characterization import characterize_source
from .models.severity import HazardZoneRadiiDTO, calculate_hazard_zone_radii
from .models.threat_polygons import HazardPolygonsDTO, generate_all_hazard_polygons
from .models.spatial_grid import HazardGridDTO, generate_hazard_grid
from .models.safe_approach import SafeApproachPlanDTO, generate_safe_approach_plan
from .models.monte_carlo import (
    MonteCarloResultDTO,
    MonteCarloInputUncertaintyDTO,
    run_monte_carlo_simulation,
)


@dataclass(frozen=True)
class HazardModelResultDTO:
    """Master consequence analysis payload generated by the deterministic physics pipeline."""
    model_version: str
    specification_id: str
    system_classification: str
    provenance_hash: str
    execution_timestamp_utc: str
    execution_duration_ms: float

    scenario: ScenarioInputDTO
    material: MaterialPropertiesDTO
    source: SourceTermsDTO
    radii: HazardZoneRadiiDTO
    polygons: HazardPolygonsDTO
    safe_approach: SafeApproachPlanDTO

    spatial_grid: Optional[HazardGridDTO] = None
    monte_carlo: Optional[MonteCarloResultDTO] = None
    warnings: List[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert result DTO into comprehensive JSON-serializable dictionary."""
        d = {
            "model_version": self.model_version,
            "specification_id": self.specification_id,
            "system_classification": self.system_classification,
            "provenance_hash": self.provenance_hash,
            "execution_timestamp_utc": self.execution_timestamp_utc,
            "execution_duration_ms": self.execution_duration_ms,
            "scenario": self.scenario.to_dict(),
            "material": self.material.to_dict(),
            "source": self.source.to_dict(),
            "radii": self.radii.to_dict(),
            "polygons": self.polygons.to_dict(),
            "safe_approach": self.safe_approach.to_dict(),
            "warnings": self.warnings or [],
        }
        if self.monte_carlo is not None:
            d["monte_carlo"] = self.monte_carlo.to_dict()
        return d

    def to_geojson(self) -> Dict[str, Any]:
        """Convert hazard zone polygons into standard GeoJSON FeatureCollection."""
        features = []
        poly_map = [
            ("RED_CRITICAL", self.polygons.red_critical, "#FF0000", 0.6),
            ("ORANGE_SEVERE", self.polygons.orange_severe, "#FF8C00", 0.45),
            ("YELLOW_MODERATE", self.polygons.yellow_moderate, "#FFD700", 0.3),
            ("GREEN_ADVISORY", self.polygons.green_advisory, "#32CD32", 0.15),
        ]

        for level_name, poly_dto, color_hex, opacity in poly_map:
            # GeoJSON uses [longitude, latitude] coordinates format
            geojson_coords = [[pt[1], pt[0]] for pt in poly_dto.coordinates]
            feature = {
                "type": "Feature",
                "properties": {
                    "hazard_level": level_name,
                    "nominal_radius_m": poly_dto.nominal_radius_m,
                    "area_m2": poly_dto.area_m2,
                    "stroke": color_hex,
                    "fill": color_hex,
                    "fill-opacity": opacity,
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [geojson_coords],
                },
            }
            features.append(feature)

        return {
            "type": "FeatureCollection",
            "metadata": {
                "specification_id": self.specification_id,
                "model_version": self.model_version,
                "provenance_hash": self.provenance_hash,
                "timestamp_utc": self.execution_timestamp_utc,
            },
            "features": features,
        }


def _compute_provenance_hash(scenario_dict: Dict[str, Any]) -> str:
    """Compute deterministic SHA256 provenance signature of the scenario inputs."""
    serialized = json.dumps(scenario_dict, sort_keys=True)
    full_string = f"{SPECIFICATION_ID}:{MODEL_VERSION}:{serialized}"
    return hashlib.sha256(full_string.encode("utf-8")).hexdigest()


def run_hazard_model(
    scenario_input: Union[Dict[str, Any], ScenarioInputDTO],
    include_spatial_grid: bool = False,
    grid_extent_m: float = 2000.0,
    grid_resolution_m: float = 25.0,
    run_monte_carlo: bool = False,
    monte_carlo_samples: int = 1000,
    monte_carlo_uncertainty: Optional[MonteCarloInputUncertaintyDTO] = None,
    monte_carlo_seed: int = 42,
) -> HazardModelResultDTO:
    """
    Execute full industrial fire & explosion hazard computational pipeline:
    1. Validate scenario inputs & build scenario DTO (Phase 1)
    2. Retrieve validated thermophysical material properties (Phase 2)
    3. Characterize physical source release terms (Phase 3)
    4. Compute exact hazard zone radii via root finding (Phase 8)
    5. Construct closed WGS84 threat zone boundary polygons (Phase 9)
    6. Generate tactical responder approach vectors & exclusion zones (Phase 10)
    7. Generate 2D continuous Cartesian spatial hazard field (Optional, Phase 7)
    8. Propagate stochastic Monte Carlo uncertainties (Optional, Phase 11)
    """
    t_start = time.perf_counter()
    warnings: List[str] = []

    # 1. Scenario Validation & Ingestion
    if isinstance(scenario_input, ScenarioInputDTO):
        scenario = scenario_input
        raw_dict = scenario.to_dict()
    else:
        raw_dict = dict(scenario_input)
        scenario = validate_and_build_scenario(raw_dict)

    provenance_hash = _compute_provenance_hash(raw_dict)

    # 2. Material Property Resolution
    material = MaterialRegistry.get(scenario.tank.material_id)

    # 3. Source Characterization
    source = characterize_source(scenario, material)

    # 4. Severity Classification & Zone Radii Determination
    radii = calculate_hazard_zone_radii(scenario, source, material)

    # 5. Geometric Threat Zone Boundaries
    polygons = generate_all_hazard_polygons(scenario, source, material, radii)

    # 6. Safe Approach Tactical Ingress Planning
    safe_approach = generate_safe_approach_plan(scenario, source, material, radii)

    # 7. Spatial Grid (Optional)
    spatial_grid: Optional[HazardGridDTO] = None
    if include_spatial_grid:
        spatial_grid = generate_hazard_grid(
            scenario, source, material, extent_m=grid_extent_m, resolution_m=grid_resolution_m
        )

    # 8. Monte Carlo Simulation (Optional)
    monte_carlo: Optional[MonteCarloResultDTO] = None
    if run_monte_carlo:
        monte_carlo = run_monte_carlo_simulation(
            scenario,
            source,
            material,
            n_samples=monte_carlo_samples,
            uncertainty=monte_carlo_uncertainty,
            seed=monte_carlo_seed,
        )

    t_elapsed_ms = (time.perf_counter() - t_start) * 1000.0

    return HazardModelResultDTO(
        model_version=MODEL_VERSION,
        specification_id=SPECIFICATION_ID,
        system_classification=SYSTEM_CLASSIFICATION,
        provenance_hash=provenance_hash,
        execution_timestamp_utc=datetime.now(timezone.utc).isoformat(),
        execution_duration_ms=float(t_elapsed_ms),
        scenario=scenario,
        material=material,
        source=source,
        radii=radii,
        polygons=polygons,
        safe_approach=safe_approach,
        spatial_grid=spatial_grid,
        monte_carlo=monte_carlo,
        warnings=warnings,
    )
