# Generated by Django 5.1.15 on 2026-08-31 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Operation Chennai Deluge 2026', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tick_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('weather_condition', models.CharField(default='HEAVY_DOWNPOUR', max_length=100)),
                ('water_level_multiplier', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ROAD_BLOCKED', 'Road / Bridge Blocked'), ('HOSPITAL_SURGE', 'Hospital Saturation Divert'), ('NEW_INCIDENT', 'Surge Incident Burst'), ('RESOURCE_FAILURE', 'Resource Breakdown'), ('WEATHER_ESCALATED', 'Rainfall / Flood Escalation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('details', models.JSONField(default=dict)),
                ('is_applied', models.BooleanField(default=False)),
                ('simulated_minute', models.PositiveIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.simulationscenario')),
            ],
            options={
                'ordering': ['simulated_minute', 'created_at'],
            },
        ),
    ]
