# Generated by Django 5.1.15 on 2026-08-31 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('incidents', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed Assignment'), ('APPROVED', 'Approved by Coordinator'), ('DISPATCHED', 'Unit Dispatched'), ('COMPLETED', 'Operation Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PROPOSED', max_length=30)),
                ('route_geometry', models.JSONField(default=list)),
                ('distance_km', models.FloatField(default=0.0)),
                ('eta_minutes', models.FloatField(default=0.0)),
                ('mathematical_rationale', models.JSONField(default=dict)),
                ('narrative_explanation', models.TextField(blank=True, default='')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='incidents.incident')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='resources.resource')),
                ('target_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dispatches', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
