# Generated by Django 5.1.15 on 2026-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintUploadCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('site_name', models.CharField(default='Industrial Facility', max_length=255)),
                ('image_width', models.IntegerField(default=1200)),
                ('image_height', models.IntegerField(default=900)),
                ('analysis_json', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('asset_id', models.CharField(max_length=64)),
                ('bbox_json', models.JSONField(default=dict)),
                ('raw_prediction', models.CharField(max_length=64)),
                ('corrected_class', models.CharField(max_length=64)),
                ('ocr_context', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
