# Generated by Django 5.1.15 on 2026-08-31 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Urban Flood'), ('FIRE', 'Fire Hazard'), ('MEDICAL', 'Medical Emergency'), ('STRUCTURAL_COLLAPSE', 'Structural Collapse')], default='FLOOD', max_length=50)),
                ('people_affected', models.PositiveIntegerField(default=1)),
                ('vulnerable_people', models.PositiveIntegerField(default=0)),
                ('vulnerability_flags', models.JSONField(default=list)),
                ('medical_need', models.BooleanField(default=False)),
                ('mobility_status', models.CharField(default='AMBULATORY', max_length=50)),
                ('urgency', models.CharField(default='URGENT', max_length=50)),
                ('calculated_priority', models.FloatField(db_index=True, default=0.0)),
                ('priority_tier', models.CharField(choices=[('CRITICAL', 'Tier 1 - Critical'), ('HIGH', 'Tier 2 - High'), ('MEDIUM', 'Tier 3 - Medium'), ('LOW', 'Tier 4 - Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('PARSED', 'AI Parsed'), ('TRIAGED', 'Triaged'), ('DISPATCHED', 'Dispatched'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='REPORTED', max_length=30)),
                ('reporter_name', models.CharField(blank=True, default='Citizen', max_length=150)),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-calculated_priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'calculated_priority'], name='incidents_i_status_f45f07_idx'), models.Index(fields=['latitude', 'longitude'], name='incidents_i_latitud_53102f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentVictim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='General Adult', max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('special_condition', models.CharField(blank=True, default='', max_length=255)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='incidents.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
