# Generated by Django 5.1.15 on 2026-08-31 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('call_sign', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('AMBULANCE_BLS', 'Basic Life Support Ambulance'), ('AMBULANCE_ALS', 'Advanced Life Support Ambulance'), ('RESCUE_BOAT', 'Inflatable Flood Rescue Boat'), ('NDRF_TEAM', 'NDRF Tactical Rescue Team'), ('FIRE_ENGINE', 'Heavy Fire Tender'), ('EVACUATION_BUS', 'Evacuation Transit Bus')], default='AMBULANCE_BLS', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE_INCIDENT', 'En Route to Incident'), ('ON_SCENE', 'On Scene'), ('TRANSPORTING_HOSPITAL', 'Transporting to Hospital'), ('RETURNING', 'Returning to Base'), ('OFFLINE', 'Offline / Maintenance')], db_index=True, default='AVAILABLE', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('capabilities', models.JSONField(default=list)),
                ('contact_radio', models.CharField(blank=True, default='CH-04', max_length=50)),
                ('base_station', models.CharField(blank=True, default='Central Station', max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
